local ok, lint = pcall(require, "lint")
if not ok then return end

-- Enable a useful default check set when no .clang-tidy file exists in the project.
-- Projects with their own .clang-tidy take precedence (clang-tidy merges args).
lint.linters.clangtidy.args = {
  "--quiet",
  "--checks=bugprone-*,modernize-*,performance-*,readability-simplify-*",
}
-- Run clang-tidy from the file's own directory so it searches upward for
-- compile_commands.json from the right starting point (e.g. files on /media/...).
lint.linters.clangtidy.cwd = function()
  return vim.fn.fnamemodify(vim.api.nvim_buf_get_name(0), ":h")
end

lint.linters_by_ft = {
  -- shellcheck catches issues bashls misses (SC codes, portability, etc.)
  sh   = { "shellcheck" },
  bash = { "shellcheck" },
  -- Python: ruff (LSP) and pyright already cover linting/types; omitted here.
  -- clangtidy adds checks beyond clangd: modernize-*, bugprone-*, performance-*.
  -- Requires compile_commands.json at the project root (generated by :MesonSetup or cmake).
  c   = { "clangtidy" },
  cpp = { "clangtidy" },
}

local slow_ft = { c = true, cpp = true }

-- clang-tidy is slow (full AST re-parse) — only run it on save to avoid lag
-- when leaving insert mode. Fast linters (shellcheck) still run on InsertLeave.
vim.api.nvim_create_autocmd("BufWritePost", {
  callback = function() lint.try_lint() end,
})
vim.api.nvim_create_autocmd("InsertLeave", {
  callback = function()
    if not slow_ft[vim.bo.filetype] then
      lint.try_lint()
    end
  end,
})
