local ok, lint = pcall(require, "lint")
if not ok then return end
-- Enable a useful default check set when no .clang-tidy file exists in the project.
-- Projects with their own .clang-tidy take precedence (clang-tidy merges args).
lint.linters.clangtidy.args = {
  "--quiet",
  "--checks=bugprone-*,modernize-*,performance-*,readability-simplify-*,-modernize-use-trailing-return-type,-modernize-return-braced-init-list",
}

lint.linters_by_ft = {
  -- shellcheck catches issues bashls misses (SC codes, portability, etc.)
  sh   = { "shellcheck" },
  bash = { "shellcheck" },
  -- Python: ruff (LSP) and pyright already cover linting/types; omitted here.
  -- clangtidy adds checks beyond clangd: modernize-*, bugprone-*, performance-*.
  -- Requires compile_commands.json at the project root (generated by :MesonSetup or cmake).
  c   = { "clangtidy" },
  cpp = { "clangtidy" },
}

local slow_ft = { c = true, cpp = true }

-- Named group prevents duplicate autocmds when config is reloaded.
local group = vim.api.nvim_create_augroup("nvim_lint", { clear = true })

-- clang-tidy is slow (full AST re-parse) — only run it on save to avoid lag
-- when leaving insert mode. Fast linters (shellcheck) still run on InsertLeave.
-- Pass cwd = file's directory so clang-tidy searches upward from there for
-- compile_commands.json (handles files on /media/... or other non-cwd paths).
vim.api.nvim_create_autocmd("BufWritePost", {
  group = group,
  callback = function()
    local ft = vim.bo.filetype
    if slow_ft[ft] then
      lint.try_lint(nil, { cwd = vim.fn.expand("%:p:h") })
    else
      lint.try_lint()
    end
  end,
})
vim.api.nvim_create_autocmd("InsertLeave", {
  group = group,
  callback = function()
    if not slow_ft[vim.bo.filetype] then
      lint.try_lint()
    end
  end,
})
