local wk = require("which-key")

wk.setup {
  preset = "modern",
  icons  = { mappings = false },
}

-- ── Group labels ──────────────────────────────────────────────────────────
-- These appear as section headers in the which-key popup when you pause
-- after pressing the leader key or a prefix.
wk.add {
  -- leader groups
  { "<leader><cr>", desc = "clear search highlight" },
  -- flash.nvim (replaces hop.nvim) — f/F/t/T are enhanced in place, no remap needed
  { "s", mode = { "n", "x" }, desc = "flash: jump" },
  { "S", mode = { "n", "x" }, desc = "flash: treesitter select" },
  { "<leader>a",  group = "C/C++ (clangd)" },
  { "<leader>as", desc = "clangd: switch source/header" },
  { "<leader>at", desc = "clangd: view AST" },
  { "<leader>ai", desc = "clangd: symbol info" },
  { "<leader>mu", desc = "clangd: memory usage" },
  { "<leader>c",  group = "cscope" },
  { "<leader>d",  group = "debug (DAP)" },
  { "<leader>f",  group = "find (fzf-lua)" },
  { "<leader>fk", desc = "search keymaps (fuzzy)" },
  { "<leader>ft", desc = "find TODO/FIXME/HACK/NOTE (todo-comments)" },
  { "<leader>g",   group = "git" },
  { "<leader>gl",  desc = "lazygit" },
  { "<leader>gL",  mode = { "n", "v" }, desc = "Git: get permlink (gitlinker)" },
  -- Fugitive
  { "<leader>gs",  desc = "Git: status (Fugitive)" },
  { "<leader>gw",  desc = "Git: stage current file" },
  { "<leader>gc",  desc = "Git: commit" },
  { "<leader>gpl", desc = "Git: pull" },
  { "<leader>gpu", desc = "Git: push (terminal split)" },
  { "<leader>gb",  mode = "v", desc = "Git: blame selection" },
  { "<leader>gd",  desc = "Git: diff split" },
  { "<leader>ge",  desc = "Git: edit file at HEAD" },
  { "<leader>gf",  desc = "Git: fetch (prompt remote)" },
  { "<leader>gbn", desc = "Git: new branch" },
  { "<leader>gbd", desc = "Git: delete branch" },
  { "<leader>gbr", desc = "Git: browse repo in browser" },
  -- Neogit
  { "<leader>gg",  group = "neogit" },
  { "<leader>ggc", desc = "Neogit: commit popup" },
  { "<leader>ggp", desc = "Neogit: push popup" },
  { "<leader>ggP", desc = "Neogit: pull popup" },
  { "<leader>ggr", desc = "Neogit: rebase popup" },
  { "<leader>ggl", desc = "Neogit: log popup" },
  { "<leader>ggA", desc = "Neogit: amend last commit" },
  { "<leader>gga", desc = "Neogit: amend (no edit)" },
  { "<leader>ggR", desc = "Neogit: rebase -i HEAD~N" },
  -- Gitsigns
  { "<leader>h",   group = "git hunks" },
  { "<leader>hp",  desc = "gitsigns: preview hunk" },
  { "<leader>hb",  desc = "gitsigns: blame line" },
  { "<leader>k",  group = "kernel (OpenBMC/Yocto)" },
  { "<leader>ks", desc = "kernel: gen compile_commands + .clangd" },
  { "<leader>kp", desc = "OE pkg: link bitbake compile_commands.json" },
  { "<leader>l",  group = "LSP peek (glance)" },
  { "<leader>la", desc = "LSP: code action" },
  { "<leader>lc", desc = "change cwd to current file's dir (lcd)" },
  { "<leader>ld", desc = "LSP: peek definitions (glance)" },
  { "<leader>lr", desc = "LSP: peek references (glance)" },
  { "<leader>li", desc = "LSP: peek implementations (glance)" },
  { "<leader>m",  group = "meson / mark" },
  { "<leader>ms", desc = "meson setup" },
  { "<leader>mb", desc = "meson build" },
  { "<leader>ml", desc = "meson re-link" },
  { "<leader>mk", desc = "mark: toggle mark on word/selection" },
  { "<leader>mK", desc = "mark: clear all marks" },
  { "<leader>r",  group = "replace / rename" },
  { "<leader>rn", desc = "LSP: rename symbol (inc-rename)" },
  { "<leader>rp", desc = "project find & replace (grug-far)" },
  { "<leader>rw", desc = "project replace word under cursor" },
  { "<leader>s",  group = "session / search / vimrc" },
  { "<leader>ss", desc = "session: toggle recording (obsession)" },
  { "<leader>sr", desc = "session: restore from Session.vim" },
  { "<leader>sv", desc = "reload vimrc / init.lua" },
  { "<leader>ev", desc = "open init.lua in new tab" },
  { "<leader>sh", desc = "LSP: signature help" },
  { "<leader>sd", mode = { "n", "x" }, desc = "grep in chosen dir (fzf-lua)" },
  { "<leader>sD", mode = { "n", "x" }, desc = "grep in multiple dirs (fzf-lua)" },
  { "<leader>W",  group = "LSP workspace" },
  { "<leader>Wa", desc = "LSP: add workspace folder" },
  { "<leader>Wr", desc = "LSP: remove workspace folder" },
  { "<leader>Wl", desc = "LSP: list workspace folders" },
  { "<leader>x",  group = "trouble / diagnostics" },
  { "<leader>ak",  group = "ack search" },
  { "<leader>akk", desc = "Ack: open literal search prompt" },
  { "<leader>akr", desc = "Ack: open regex prompt" },
  { "<leader>akc", desc = "Ack: clear highlights" },
  { "<leader>ao", desc = "aerial: toggle symbol outline" },
  { "<leader>n",  group = "file explorer" },
  { "<leader>nn", desc = "nvim-tree: toggle" },
  { "<leader>nf", desc = "nvim-tree: reveal current file" },
  { "<leader>nF", desc = "nvim-tree: focus" },
  { "<leader>o",  group = "overseer (tasks)" },
  { "<leader>ot", desc = "overseer: toggle task list" },
  { "<leader>or", desc = "overseer: run task template" },
  { "<leader>oR", desc = "overseer: run shell command" },
  { "<leader>t",  group = "toggle / tab" },
  { "<leader>tt", desc = "toggle floating terminal" },
  { "<leader>tf", desc = "toggle format on save" },
  { "<leader>tn", desc = "tab: new" },
  { "<leader>tc", desc = "tab: close" },
  { "<F6>",       desc = "tab: close" },
  { "<F7>",       desc = "tab: prev" },
  { "<F8>",       desc = "tab: next" },
  { "<leader>fm", desc = "toggle fold method expr/manual" },
  { "<leader>K",  desc = "preview folded lines (ufo)" },
  { "<leader>fy", desc = "yank ring history (yanky)" },
  { "<leader>H",  group = "harpoon" },
  { "<leader>Ha", desc = "harpoon: add file" },
  { "<leader>Hh", desc = "harpoon: menu" },
  { "<leader>1",  desc = "harpoon: jump to 1" },
  { "<leader>2",  desc = "harpoon: jump to 2" },
  { "<leader>3",  desc = "harpoon: jump to 3" },
  { "<leader>4",  desc = "harpoon: jump to 4" },
  { "<leader>A",  group = "Claude Code CLI" },
  { "<leader>Ac", desc = "Claude: toggle" },
  { "<leader>Af", desc = "Claude: focus" },
  { "<leader>Ar", desc = "Claude: resume session" },
  { "<leader>AC", desc = "Claude: continue session" },
  { "<leader>Am", desc = "Claude: select model" },
  { "<leader>Ab", desc = "Claude: add current buffer" },
  { "<leader>As", desc = "Claude: send selection" },
  { "<leader>Aa", desc = "Claude: accept diff" },
  { "<leader>Ad", desc = "Claude: deny diff" },
  { "<leader>u",  group = "UI toggles" },
  -- UI toggle entries
  { "<leader>ub", desc = "blink cursor to locate it" },
  { "<leader>uc", desc = "pick colorscheme (fzf-lua)" },
  { "<leader>ud", desc = "toggle diagnostics" },
  { "<leader>uD", desc = "toggle diagnostic float" },
  { "<leader>ih", desc = "toggle inlay hints (all LSP clients)" },
  { "<leader>ul", desc = "toggle cursor column" },
  { "<leader>um", desc = "toggle undo tree (mundo)" },
  { "<leader>un", desc = "show notification history" },
  { "<leader>uo", desc = "open quickfix list" },
  { "<leader>uq", desc = "close quickfix list" },
  { "<leader>ux", desc = "toggle treesitter context bar" },
  -- DAP entries
  { "<leader>dc", desc = "DAP: continue" },
  { "<leader>do", desc = "DAP: step over" },
  { "<leader>di", desc = "DAP: step into" },
  { "<leader>dO", desc = "DAP: step out" },
  { "<leader>db", desc = "DAP: toggle breakpoint" },
  { "<leader>dB", desc = "DAP: conditional breakpoint" },
  { "<leader>dL", desc = "DAP: log point" },
  { "<leader>dr", desc = "DAP: open REPL" },
  { "<leader>dl", desc = "DAP: run last" },
  { "<leader>dx", desc = "DAP: terminate" },
  { "<leader>du", desc = "toggle DAP UI" },
  { "<leader>dv", desc = "DAP: toggle virtual text" },
  -- diagnostic → quickfix
  { "<space>qw",  desc = "workspace diagnostics → quickfix" },
  { "<space>qb",  desc = "buffer diagnostics → quickfix" },
  -- Neovim 0.10+ default LSP keymaps (buffer-local when LSP attaches)
  { "grr", desc = "LSP: references" },
  { "gri", desc = "LSP: implementation" },
  { "gra", mode = { "n", "x" }, desc = "LSP: code action" },
  { "grn", desc = "LSP: rename (default; use <leader>rn for inc-rename)" },
  -- buffer / window / file operations
  { "<leader>w", desc = "save buffer" },
  { "<leader>q", desc = "save and close window" },
  { "<leader>Q", desc = "quit all (force)" },
  { "<leader>p", desc = "paste below current line (preserves cursor)" },
  { "<leader>P", desc = "paste above current line (preserves cursor)" },
  { "<leader>y", desc = "yank entire buffer" },
  { "<leader>b", desc = "new empty buffer" },
  { "<leader>te", desc = "open file browser in current file's dir" },
  -- buffer delete (backslash prefix)
  { "\\d", desc = "delete current buffer (force)" },
  { "\\D", desc = "delete other buffers (force)" },
  { "\\x", desc = "close quickfix and location list" },
  -- quickfix navigation
  { "]q", desc = "next quickfix item" },
  { "[q", desc = "prev quickfix item" },
  { "]Q", desc = "last quickfix item" },
  { "[Q", desc = "first quickfix item" },
  -- todo-comments jumps
  { "]t", desc = "next TODO comment" },
  { "[t", desc = "prev TODO comment" },
  -- hunk / error / reference navigation
  { "]c", desc = "next git hunk" },
  { "[c", desc = "prev git hunk" },
  { "]e", desc = "next error (diagnostics only)" },
  { "[e", desc = "prev error (diagnostics only)" },
  { "]r", desc = "illuminate: next reference" },
  { "[r", desc = "illuminate: prev reference" },
  -- markdown (only active in markdown buffers)
  { "<leader>mp", ft = "markdown", desc = "markdown: toggle browser preview" },
  { "<leader>mr", ft = "markdown", desc = "markdown: toggle in-editor rendering" },
  -- mini.ai textobjects (operator-pending hints)
  { "af", desc = "around function definition" },
  { "if", desc = "inner function definition" },
  { "ac", desc = "around class/struct" },
  { "ic", desc = "inner class/struct" },
  { "al", desc = "around loop" },
  { "il", desc = "inner loop" },
  { "aL", desc = "around last textobject (prev)" },
  { "iL", desc = "inner last textobject (prev)" },
  { "ao", desc = "around conditional" },
  { "io", desc = "inner conditional" },
  { "aa", desc = "around argument" },
  { "ia", desc = "inner argument" },
}
