local wk = require("which-key")

wk.setup {
  preset = "modern",
  icons  = { mappings = false },
}

-- ── Group labels ──────────────────────────────────────────────────────────
-- These appear as section headers in the which-key popup when you pause
-- after pressing the leader key or a prefix.
wk.add {
  -- leader groups
  { "<leader><cr>", desc = "clear search highlight" },
  { "<leader>a",  group = "C/C++ (clangd)" },
  { "<leader>as", desc = "clangd: switch source/header" },
  { "<leader>at", desc = "clangd: view AST" },
  { "<leader>si", desc = "clangd: symbol info" },
  { "<leader>mu", desc = "clangd: memory usage" },
  { "<leader>c",  group = "cscope" },
  { "<leader>d",  group = "debug (DAP)" },
  { "<leader>f",  group = "find (fzf-lua)" },
  { "<leader>g",  group = "git" },
  { "<leader>gl", desc = "lazygit" },
  { "<leader>gg", group = "neogit" },
  { "<leader>h",  group = "git hunks" },
  { "<leader>k",  group = "kernel (OpenBMC/Yocto)" },
  { "<leader>ks", desc = "kernel: gen compile_commands + .clangd" },
  { "<leader>kp", desc = "OE pkg: link bitbake compile_commands.json" },
  { "<leader>l",  group = "LSP peek (glance)" },
  { "<leader>m",  group = "meson / mark" },
  { "<leader>ms", desc = "meson setup" },
  { "<leader>mb", desc = "meson build" },
  { "<leader>ml", desc = "meson re-link" },
  { "<leader>mk", desc = "mark: toggle mark on word/selection" },
  { "<leader>mK", desc = "mark: clear all marks" },
  { "<leader>r",  group = "replace / rename" },
  { "<leader>rp", desc = "project find & replace (grug-far)" },
  { "<leader>rw", desc = "project replace word under cursor" },
  { "<leader>s",  group = "vimrc" },
  { "<leader>sv", desc = "reload vimrc / init.lua" },
  { "<leader>w",  group = "LSP workspace" },
  { "<leader>x",  group = "trouble / diagnostics" },
  { "<leader>ak", group = "ack search" },
  { "<leader>ao", desc = "aerial: toggle symbol outline" },
  { "<leader>n",  group = "file explorer (NERDTree)" },
  { "<leader>o",  group = "overseer (tasks)" },
  { "<leader>ot", desc = "overseer: toggle task list" },
  { "<leader>or", desc = "overseer: run task template" },
  { "<leader>oR", desc = "overseer: run shell command" },
  { "<leader>t",  group = "toggle" },
  { "<leader>tt", desc = "toggle floating terminal" },
  { "<leader>tf", desc = "toggle format on save" },
  { "<leader>fm", desc = "toggle fold method expr/manual" },
  { "<leader>A",  group = "Claude Code CLI" },
  { "<leader>Ac", desc = "Claude: toggle" },
  { "<leader>Af", desc = "Claude: focus" },
  { "<leader>Ar", desc = "Claude: resume session" },
  { "<leader>AC", desc = "Claude: continue session" },
  { "<leader>Am", desc = "Claude: select model" },
  { "<leader>Ab", desc = "Claude: add current buffer" },
  { "<leader>As", desc = "Claude: send selection" },
  { "<leader>Aa", desc = "Claude: accept diff" },
  { "<leader>Ad", desc = "Claude: deny diff" },
  { "<leader>u",  group = "UI toggles" },
  -- UI toggle entries
  { "<leader>ub", desc = "blink cursor to locate it" },
  { "<leader>uc", desc = "pick colorscheme (fzf-lua)" },
  { "<leader>ud", desc = "toggle diagnostics" },
  { "<leader>uD", desc = "toggle diagnostic float" },
  { "<leader>ih", desc = "toggle inlay hints (clangd)" },
  { "<leader>un", desc = "show notification history" },
  { "<leader>ux", desc = "toggle treesitter context bar" },
  -- DAP entries
  { "<leader>dc", desc = "DAP: continue" },
  { "<leader>do", desc = "DAP: step over" },
  { "<leader>di", desc = "DAP: step into" },
  { "<leader>dO", desc = "DAP: step out" },
  { "<leader>db", desc = "DAP: toggle breakpoint" },
  { "<leader>dB", desc = "DAP: conditional breakpoint" },
  { "<leader>dL", desc = "DAP: log point" },
  { "<leader>dr", desc = "DAP: open REPL" },
  { "<leader>dl", desc = "DAP: run last" },
  { "<leader>dx", desc = "DAP: terminate" },
  { "<leader>du", desc = "toggle DAP UI" },
  { "<leader>dv", desc = "DAP: toggle virtual text" },
  -- quickfix
  { "<leader>co", desc = "open quickfix list" },
  { "<leader>cc", desc = "close quickfix list" },
  -- diagnostic → quickfix
  { "<space>qw",  desc = "window diagnostics → quickfix" },
  { "<space>qb",  desc = "buffer diagnostics → quickfix" },
  -- todo-comments jumps
  { "]t", desc = "next TODO comment" },
  { "[t", desc = "prev TODO comment" },
  -- mini.ai textobjects (operator-pending hints)
  { "af", desc = "around function definition" },
  { "if", desc = "inner function definition" },
  { "ac", desc = "around class/struct" },
  { "ic", desc = "inner class/struct" },
  { "aa", desc = "around argument" },
  { "ia", desc = "inner argument" },
}
