return {
  filetypes = { "c", "cpp", "cc" },
  root_markers = {
    "compile_commands.json",  -- meson/cmake build
    "compile_flags.txt",
    ".clangd",
    "meson.build",
    "CMakeLists.txt",
    ".git",
  },
  -- Allow clangd to query Yocto/OpenBMC cross-compilers for built-in
  -- includes and defines. The glob covers typical arm-*-linux-gnueabi
  -- toolchains generated by Yocto inside a build/tmp/sysroots tree.
  cmd = {
    "clangd",
    "--query-driver=**/arm-*-linux-*-gcc*,**/arm-*-linux-*-g++*",
  },
}
